spring.application.name=productservice
# Active Profile: 'db' for database implementation, 'fakestore' for external API
spring.profiles.active=db
spring.jpa.hibernate.ddl-auto=update
spring.datasource.url=jdbc:mysql://localhost:3306/productdb
spring.datasource.username=root
spring.datasource.password=password
spring.jpa.show-sql= true